# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  package_version: 0.0.1

trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:

- script: echo $PATH
  displayName: Check PATH environment variable

- task: Hey24sheep.flutter.flutter-install.FlutterInstall@0
  displayName: 'Flutter Install'

- script :  flutter doctor
  displayName : Run flutter doctor

- script: flutter pub get
  displayName: Install dependencies

- script: flutter analyze
  displayName: Analyze code

- script: flutter test
  displayName: Run tests

# - task: qetza.replacetokens.replacetokens-task.replacetokens@5
#   displayName: 'Set version number'
#   inputs:
#     targetFiles: pubspec.yaml
#     tokenPattern: doublebraces
#     keepToken: true
#     actionOnNoFiles: warn

- script: |
    latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
    echo "Latest Tag: $latest_tag"
    flutter pub publish --access-token $(PUB_DEV_TOKEN) --package-name="$latest_tag" build/my_package.tar.gz
  displayName: 'Publish to pub.dev'

# - script: |
#     flutter pub publish --access-token $(PUB_DEV_TOKEN)
#   displayName: Publish to pub.dev
#   env:
#     PUB_DEV_TOKEN: $(PUB_DEV_TOKEN)  # Use the secure variable

- publish: $(System.DefaultWorkingDirectory)/build/artifacts
  displayName: Publish artifacts


 
# git clone https://github.com/flutter/flutter.git

# export PATH=`pwd`/flutter/bin:$PATH

# flutter channel stable

# flutter doctor

# flutter upgrade

# displayName: 'Configure flutter SDK'

  



