# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
name: Publish to pub.dev

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'

      - name: Get dependencies
        run: flutter pub get
      
      - name: Analyzing Dart code 
      - run: flutter analyze

      - name: Publish to pub.dev
        run: flutter pub publish --dry-run
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
