name: requests_signature_dart
description: "A Dart package for making HTTP requests with cryptographic signatures."
version: {{package_version}} #0.0.1
homepage: https://github.com/nventive/RequestsSignature-Dart

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  cryptography: ^2.7.0
  dio: ^5.4.1
  http: ^1.2.0
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4
  uuid: ^4.3.3

dev_dependencies:
  test: ^1.25.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec