name: requests_signature_dart
description: "a Dart package for making HTTP requests with cryptographic signatures."
version: {{package_version}}
homepage: https://github.com/nventive/RequestsSignature-Dart

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  cryptography: ^2.7.0
  dio: ^5.4.1
  http_mock_adapter: ^0.6.1
  uuid: ^4.3.3

dev_dependencies:
  test: ^1.25.2